[SKIN_CPU_MONITOR]
algo_type        monitor
sampling         1000
sensor           skin-msm-therm
thresholds       44000                       46000                       50000                              54000
thresholds_clr   42000                       44000                       48000                              52000
actions          cpu2+cpu5+cpu7              cpu2+cpu5+cpu7              cpu0+cpu2+cpu5+cpu7                cpu0+cpu2+cpu5+cpu7
action_info      2707200+2707200+3052800     2515200+2515200+2630400     1670400+1708800+1708800+1708800    902400+960000+960000+902400

[SKIN_GPU_MONITOR]
algo_type      monitor
sampling       1000
sensor         skin-msm-therm
thresholds     44000         46000         52000            53000          54000
thresholds_clr 43000         45000         51000            52000          53000
actions        gpu           gpu           gpu              gpu            gpu
action_info    903000000     834000000     629000000        578000000      366000000

[BATTERY_MONITOR]
algo_type monitor
sampling 1000
sensor         skin-msm-therm
thresholds     41000   42000   43000    45000    46000     47000     49000    51000
thresholds_clr 39000   41000   42000    43000    45000     46000     47000    49000
actions        battery battery battery  battery  battery   battery   battery  battery
action_info    2       3       4        5        6         7         8        10
